defmodule Community.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:resident) do
      modify :unit, :text, null: true
      add :admin, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:resident) do
      remove :admin
      modify :unit, :text, null: false
    end
  end
end
