defmodule Community.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:resident) do
      add :account_number, :text
      add :name, :text
    end
  end

  def down do
    alter table(:resident) do
      remove :name
      remove :account_number
    end
  end
end