defmodule Community.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :firebase_id, :text, null: false
      add :approved, :boolean, null: false, default: false
      add :owner, :boolean, null: false, default: false
      add :unit, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:user, [:firebase_id], name: "user_firebase_id_index")

    create table(:announcement, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :body, :text, null: false
      add :renter_viewable, :boolean, null: false, default: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    drop table(:announcement)

    drop_if_exists unique_index(:user, [:firebase_id], name: "user_firebase_id_index")

    drop table(:user)
  end
end